### ISSUE TITLE
clang-tidy execute error

### ISSUE THREAD

**Issue by youngjae-avikus** [franneck94/CppProjectTemplate#6]
Hi, I'm proceeding to the command below, but there's an error

```bash
make prepare
make install
cmake .. -G "Unix Makefiles"
cmake --build . -j$(nproc)
cmake --build . --target main_clangtidy
```

```bash
cmake --build . --target main_clangtidy
LLVM ERROR: CommonOptionsParser: failed to parse command-line arguments. [CommonOptionsParser]: clang-tidy: Unknown command line argument '--config-file=/workspace/CppProjectTemplate/.clang-tidy'.  Try: '/usr/bin/clang-tidy --help'
clang-tidy: Did you mean '--config=/workspace/CppProjectTemplate/.clang-tidy'?

Unable to run clang-tidy.
make[3]: *** [app/CMakeFiles/main_clangtidy.dir/build.make:70: app/CMakeFiles/main_clangtidy] Error 1
make[2]: *** [CMakeFiles/Makefile2:480: app/CMakeFiles/main_clangtidy.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:487: app/CMakeFiles/main_clangtidy.dir/rule] Error 2
make: *** [Makefile:260: main_clangtidy] Error 
```

**Comment by franneck94** [comment]
Most likely, you need to upgrade your clang tidy version

**Comment by youngjae-avikus** [comment]
I'm doing it inside the docker container, but I searched it and it seems to be related to the docker, so could you tell me?

and I use clang-tidy version 1.10.0

**Comment by franneck94** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/20141069/219062014-478865c0-c976-4e1d-905c-520111f933e1.png)

Are you sure with 1.10?

There is already 14 and newer

**Comment by youngjae-avikus** [comment]
@franneck94 
https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-07.html
The container I use is the same as above, but I think there is a limit to the apt... So, is it a way to build a source for clang-tidy?
Cppcheck works, but it's frustrating that it doesn't work.

**Comment by franneck94** [comment]
I wouldnt recommend this
