### ISSUE TITLE
conan cann't use

### ISSUE THREAD

**Issue by Nicooo-Wang** [franneck94/CppProjectTemplate#8]
when i run `conan install .. --build missing`
```
nico@nico-desktop:~/code/CppProjectTemplate/build
(master)$ conan install .. --build missing
```
It metioned below
```
======== Finalizing install (deploy, generators) ========
conanfile.txt: Writing generators to /home/nico/code/CppProjectTemplate
ERROR: Invalid generator 'cmake_find_package'. Available types: CMakeToolchain, CMakeDeps, MesonToolchain, MSBuildDeps, MSBuildToolchain, NMakeToolchain, NMakeDeps, VCVars, QbsProfile, VirtualRunEnv, VirtualBuildEnv, AutotoolsDeps, AutotoolsToolchain, PkgConfigDeps, BazelDeps, BazelToolchain, IntelCC, XcodeDeps, XcodeToolchain, PremakeDeps
```
How can i fix it?
conan version is 2.04
gcc version is 9.4.0

Thank you tutor, your course is great, but hope you can make a course step by step tell us how to integrate conan/clang-tidy/vcpkg into our CMake project! Otherwise, we don't know how to fix the problem when we compile the system error, the template project is a bit too complicated.

Meanwhile, I have some questions, such as how to add more external libs into conan and vcpkg, how does `main` executable file find liblib.so in system? This problem is encountered when we want to move the executable to another location.

**Comment by franneck94** [comment]
Please post further questions on Udemy

**Comment by franneck94** [comment]
Can you try using this conan version?
https://pypi.org/project/conan/1.59.0/

pip install conan==1.59.0

**Comment by Nicooo-Wang** [comment]
hi, thanks for your help!
I've solved this issue, but still encountered with another issue.
I've removed main.cc line:31-35
```
    // Compiler Warning and clang tidy error
    std::int32_t i = 0;

    // Adress Sanitizer should see this
    int *x = new int[42];
```
After this, I rebuild the project, but still meet some error
```
[proc] Executing command: /usr/local/bin/cmake --build /home/nico/code/CppProjectTemplate/build --config Debug --target run_cmake_format main -j 18 --
[build] Built target run_cmake_format
[build] [ 50%] Built target lib
[build] [ 75%] Building CXX object app/CMakeFiles/main.dir/main.cc.o
[build] [100%] Linking CXX executable main
[build] /usr/bin/ld: CMakeFiles/main.dir/main.cc.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v9::format<std::basic_string_view<char, std::char_traits<char> > const&, std::basic_string_view<char, std::char_traits<char> > const&>(fmt::v9::basic_format_string<char, fmt::v9::type_identity<std::basic_string_view<char, std::char_traits<char> > const&>::type, fmt::v9::type_identity<std::basic_string_view<char, std::char_traits<char> > const&>::type>, std::basic_string_view<char, std::char_traits<char> > const&, std::basic_string_view<char, std::char_traits<char> > const&)':
[build] /home/nico/.conan/data/fmt/9.1.0/_/_/package/30a9781670e6fb2f17b8355b17a15cf916045317/include/fmt/core.h:3206: undefined reference to `fmt::v9::vformat[abi:cxx11](fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)'
[build] collect2: error: ld returned 1 exit status
[build] make[3]: *** [app/CMakeFiles/main.dir/build.make:100: app/main] Error 1
[build] make[2]: *** [CMakeFiles/Makefile2:321: app/CMakeFiles/main.dir/all] Error 2
[build] make[1]: *** [CMakeFiles/Makefile2:328: app/CMakeFiles/main.dir/rule] Error 2
[build] make: *** [Makefile:234: main] Error 2
[proc] The command: /usr/local/bin/cmake --build /home/nico/code/CppProjectTemplate/build --config Debug --target run_cmake_format main -j 18 -- exited with code: 2
[driver] Build completed: 00:00:13.701
[build] Build finished with exit code 2
```
How is this problem caused, and how to fix the error?

**Comment by Nicooo-Wang** [comment]
> hi, thanks for your help! I've solved this issue, but still encountered with another issue. I've removed main.cc line:31-35
> 
> ```
>     // Compiler Warning and clang tidy error
>     std::int32_t i = 0;
> 
>     // Adress Sanitizer should see this
>     int *x = new int[42];
> ```
> 
> After this, I rebuild the project, but still meet some error
> 
> ```
> [proc] Executing command: /usr/local/bin/cmake --build /home/nico/code/CppProjectTemplate/build --config Debug --target run_cmake_format main -j 18 --
> [build] Built target run_cmake_format
> [build] [ 50%] Built target lib
> [build] [ 75%] Building CXX object app/CMakeFiles/main.dir/main.cc.o
> [build] [100%] Linking CXX executable main
> [build] /usr/bin/ld: CMakeFiles/main.dir/main.cc.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v9::format<std::basic_string_view<char, std::char_traits<char> > const&, std::basic_string_view<char, std::char_traits<char> > const&>(fmt::v9::basic_format_string<char, fmt::v9::type_identity<std::basic_string_view<char, std::char_traits<char> > const&>::type, fmt::v9::type_identity<std::basic_string_view<char, std::char_traits<char> > const&>::type>, std::basic_string_view<char, std::char_traits<char> > const&, std::basic_string_view<char, std::char_traits<char> > const&)':
> [build] /home/nico/.conan/data/fmt/9.1.0/_/_/package/30a9781670e6fb2f17b8355b17a15cf916045317/include/fmt/core.h:3206: undefined reference to `fmt::v9::vformat[abi:cxx11](fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)'
> [build] collect2: error: ld returned 1 exit status
> [build] make[3]: *** [app/CMakeFiles/main.dir/build.make:100: app/main] Error 1
> [build] make[2]: *** [CMakeFiles/Makefile2:321: app/CMakeFiles/main.dir/all] Error 2
> [build] make[1]: *** [CMakeFiles/Makefile2:328: app/CMakeFiles/main.dir/rule] Error 2
> [build] make: *** [Makefile:234: main] Error 2
> [proc] The command: /usr/local/bin/cmake --build /home/nico/code/CppProjectTemplate/build --config Debug --target run_cmake_format main -j 18 -- exited with code: 2
> [driver] Build completed: 00:00:13.701
> [build] Build finished with exit code 2
> ```
> 
> How is this problem caused, and how to fix the error?

sorry, i've solved this problem. thank you!
